---
dist: bionic
jobs:
  allow_failures:
    - rust: beta nightly
  fast_finish: true
  include:
    before_install:
      - ~
      - openssl aes-256-cbc -K $encrypted_cdc0677920ab_key -iv $encrypted_cdc0677920ab_iv -in secrets.tar.gz.enc -out secrets.tar.gz -d