dist: xenial
services: docker
jobs:
  allow_failures:
    - rust: beta nightly
  fast_finish: true
  include:
    before_install:
      - "echo \"deb [signed-by=/usr/share/keyrings/cloud.google.gpg] http://packages.cloud.google.com/apt cloud-sdk main\" | sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list"
      - "curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key --keyring /usr/share/keyrings/cloud.google.gpg add -"
      - sudo apt-get update -y
      - sudo apt-get install google-cloud-sdk -y
      - sudo apt-get install kubectl -y
      - openssl aes-256-cbc -K $encrypted_cdc0677920ab_key -iv $encrypted_cdc0677920ab_iv -in secrets.tar.gz.enc -out secrets.tar.gz -d
    cache: cargo
    env:
      global: CLOUDSDK_CORE_DISABLE_PROMPTS=1 CLOUDSDK_INSTALL_DIR=$HOME/google-cloud-sdk
    install:
      - pwd
      - ls
    language: rust
    rust: stable
    script:
      - pwd
      - cargo build --verbose --all
      - cargo test --verbose --all
language: rust
rust:
  - stable
  - beta
  - nightly