---
dist: bionic
jobs:
  fast_finish: true
  include:
    before_install:
      # Initialize git submodules
      - git submodule update --init --recursive
      # Install gcloud sdk
      - echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] http://packages.cloud.google.com/apt cloud-sdk main" | sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list
      - curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key --keyring /usr/share/keyrings/cloud.google.gpg add -
      - sudo apt-get update -y
      - sudo apt-get install google-cloud-sdk -y
      - sudo apt-get install kubectl -y
      # Install Terraform
      - wget https://releases.hashicorp.com/terraform/"$tf_version"/terraform_"$tf_version"_linux_amd64.zip
      - unzip terraform_"$tf_version"_linux_amd64.zip
      - sudo mv terraform /usr/local/bin/
      - rm terraform_"$tf_version"_linux_amd64.zip
    cache: cargo
    env:
      global: CLOUDSDK_CORE_DISABLE_PROMPTS=1 CLOUDSDK_INSTALL_DIR=$HOME/google-cloud-sdk tf_version=0.12.24 tf_init_cli_options="-input=false" tf_validation_cli_options="" tf_plan_cli_options="-lock=false -input=false" tf_apply_cli_options="-auto-approve -input=false"
    install:
      - pwd
      - ls
    script:
      - pwd
      - cargo build
      - cargo test -- --ignored --test-threads=1
language: rust
rust:
  - stable
  - beta
  - nightly