[scripts.b]
alias = 'b'
description = "cargo build"
command = 'cargo build'
tags = [ "cargo", "rust" ]

[scripts.r]
alias = 'r'
description = "cargo run"
command = 'cargo run'
tags = [ "cargo", "rust" ]

[scripts.t]
alias = 't'
description = "cargo test"
command = 'cargo test -- --nocapture --test-threads=1'
tags = [ "cargo", "rust" ]

[scripts.we]
alias = 'we'
description = "watch espanso restart"
command = 'cargo-watch -w espanso -s "espanso restart"'
tags = [ "espanso", "watch" ]

[scripts.wr]
alias = 'wr'
description = "watch cargo run"
command = 'cargo-watch -w src -w tests -d 15 -x run'
tags = [ "cargo", "rust" ]

[scripts.wt]
alias = 'wt'
description = "watch cargo test"
command = "cargo-watch -w src -w tests -x 'test -- --nocapture --test-threads=1'"
tags = [ "cargo", "rust" ]

[scripts.du]
alias = 'du'
description = "docker-compose up foreground"
command = 'docker-compose up'
tags = [ "docker" ]

[scripts.duu]
alias = 'dud'
description = "docker-compose up daemon"
command = 'docker-compose up -d'
tags = [ "docker" ]

[scripts.dd]
alias = 'dd'
description = "docker-compose down destroy volume"
command = 'docker-compose down -v'
tags = [ "docker" ]

[scripts.ee]
alias = 'ee'
description = "espanso edit config"
command = 'espanso edit'
tags = [ "espanso" ]

[scripts.es]
alias = 'es'
description = "espanso start"
command = 'espanso start'
tags = [ "espanso" ]

[scripts.er]
alias = 'er'
description = "espanso restart"
command = 'espanso restart'
tags = [ "espanso" ]

[scripts.ed]
alias = 'ed'
description = "espanso documentation"
command = 'open https://espanso.org/docs/'
tags = [ "espanso" ]

[scripts.ie]
alias = 'ie'
description = "install espanso"
command = 'brew tap federico-terzi/espanso && brew install espanso'
tags = [ "install", "espanso" ]

[scripts.if]
alias = 'if'
description = "install ff"
command = 'brew install vishaltelangre/tap/ff'
tags = [ "install", "ff", "find" ]

[scripts.ir]
alias = 'ir'
description = "install ripgrep"
command = 'brew install ripgrep'
tags = [ "install", "ripgrep", "find" ]

[scripts.mac-mission]
alias = ''
description = "mission control move left|right desktop"
command = 'left_command + j|;'
tags = [ "mission-control" ]

[scripts.amethyst-select]
alias = ''
description = "move mouse to monitor {num}"
command = 'left_command + right_control + {num}'
tags = [ "amethyst"]

[scripts.amethyst-move]
alias = ''
description = "move window to monitor {num}"
command = 'left_command + right_control + shift + {num}'
tags = [ "amethyst"]

[scripts.tmux-move]
alias = ''
description = "move to screen {num}"
command = 'right_control + w > {num}'
tags = [ "tmux"]

[scripts.tmux-split-V]
alias = ''
description = "split screen vertically"
command = 'right_control + w > percent(%)'
tags = [ "tmux"]

[scripts.tmux-split-H]
alias = ''
description = "split screen horizontally"
command = 'right_control + w > double-quote(")'
tags = [ "tmux"]

[scripts.tmux-split-Z]
alias = ''
description = "zoom/unzoom a screen"
command = 'right_control + w > z'
tags = [ "tmux"]

[scripts.tmux-move-LR]
alias = ''
description = "move split window left|right"
command = 'right_control + w > {|}'
tags = [ "tmux"]

[scripts.tmux-select]
alias = ''
description = "select split window up|down|left|right"
command = 'right_control + w > left_control + shift + k|j|h|l'
tags = [ "tmux"]

[scripts.tmux-close]
alias = ''
description = "close screen"
command = 'right_control + w > x'
tags = [ "tmux"]

[scripts.tmux-name]
alias = ''
description = "rename screen"
command = 'right_control + w > comma(,)'
tags = [ "tmux", "rename"]

[scripts.vim-cursor-move-num-lines]
alias = ''
description = "cursor move {num} lines up|down"
command = '{num} > j|k'
tags = [ "vim", "cursor"]

[scripts.vim-cursor-to-num-line]
alias = ''
description = "cursor move to line {num}"
command = '{num} > shift + g'
tags = [ "vim", "cursor"]

[scripts.vim-cursor-move-line]
alias = ''
description = "cursor move start|end of current line"
command = 'right_control + 0 or a|f or $'
tags = [ "vim", "cursor" ]

[scripts.vim-cursor-find-char]
alias = ''
description = "cursor move to {char} backward|forward of current line"
command = 'f > {char} > comma(,)|semicolon(;)'
tags = [ "vim", "cursor"]

[scripts.vim-cursor-move-word]
alias = ''
description = "cursor move to back|next start of word"
command = 'normal-mode > b|w'
tags = [ "vim", "cursor", "word"]

[scripts.vim-select-enclosed]
alias = ''
description = "select matching {}|()"
command = 'shift + v > percent(%)'
tags = [ "vim", "select"]

[scripts.vscode-move-split-LR]
alias = ''
description = "move split window right|left"
command = 'left_command + right_control > g|j'
tags = [ "vim", "select"]
