
# This is the default configuration file, change it as you like it
# You can refer to the official documentation:
# https://espanso.org/docs/
# Matches are the substitution rules, when you type theessstrigger" string
# it gets replaced by the "replace" string.
auto_restart: true
show_icon: false
show_notifications: false
secure_input_notification: false
 
matches:
  - trigger: ":eeee"
    replace: "espanso edit\n"
  - trigger: ":eeev"
    replace: "espanso edit vim\n"
  - trigger: ":eeeg"
    replace: "espanso edit git\n"
  - trigger: ":eeep"
    replace: "espanso edit pier\n"
  - trigger: ":eeer"
    replace: "espanso edit rust\n"
  - trigger: ":eeed"
    replace: "espanso edit dictionary\n"

  # Simple text replacement
  - trigger: "theis is a ter"
    replace: "eesss"

  - trigger: ":div"
    replace: "<div>$|$</div>"
  
  # Multiple replace
  - triggers: ["word1", "word2"]
    replace: "world"

  # Replace same character case  
  - trigger: "alh"
    replace: "although"
    propagate_case: true
    word: true

  # Dates
  - trigger: ":date"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%m/%d/%Y"
  # Images        
  - trigger: ":catimage"
    image_path: "$CONFIG/images/cat.png"
  # Shell commands
  - trigger: ":exampleshell"
    replace: "{{output}}"
    vars:
      - name: output
        type: shell
        params:
          cmd: "echo Hello from your shell"
  # Shell commands
  - trigger: ":exampleip"
    replace: "{{output}}"
    vars:
      - name: output
        type: shell
        params:
          cmd: "curl 'https://api.ipify.org'"
  - trigger: ":examplelocalip"
    replace: "{{output}}"
    vars:
      - name: output
        type: shell
        params:
          cmd: "ip a | grep 'inet 192' | awk '{ print $2 }'"
  # Python commands
  - trigger: ":pyscript"
    replace: "{{output}}"
    vars:
      - name: output
        type: script
        params:
          args:
            - python
            - /path/to/your/script.py
  # Random
  - trigger: ":examplequote"
    replace: "{{output}}"
    vars:
      - name: output
        type: random
        params:
          choices:
            - "Every moment is a fresh beginning."
            - "Everything you can imagine is real."
            - "Whatever you do, do it well."
  # Multi-lines
  - trigger: "exampleinclude newlines"
    replace: |
              exactly as you see
              will appear these three
              lines of poetry
  # Single line, folded        
  - trigger: "fold newlines"
    replace: >
              this is really a
              single line of text
              despite appearances
  # Clipboard
  - trigger: ":arstastratsasrt"
    replace: "<a href='{{clipboard}}' />$|$</a>"
    vars:
      - name: "clipboard"
        type: "clipboard"
